/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import config.dbConnector;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Macky Server
 */
public class citizenform extends javax.swing.JFrame {
    
    public citizenform() {
        initComponents();
    }      
        public void close(){
            this.dispose(); // Close the current window
            SuperAdminDashboard sad = new SuperAdminDashboard();
            sad.setVisible(true);

        }
    
        Color navcolor = new Color(204,204,204);
        Color headcolor = new Color(0,153,153);
        Color bodycolor = new Color(0,102,102);
        
        public String gender;
        public String action;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cid = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        clname = new javax.swing.JTextField();
        cgender = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cemail = new javax.swing.JTextField();
        cstatus = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        caddress = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ccontacts = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        cfname = new javax.swing.JTextField();

        jPanel1.setPreferredSize(new java.awt.Dimension(910, 590));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(790, 490));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("CITIZEN FORM");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 30));

        close.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        close.setForeground(new java.awt.Color(240, 240, 240));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel3.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 30, 30));

        minimize.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        minimize.setForeground(new java.awt.Color(240, 240, 240));
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("—");
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel3.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 30, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 50));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cid.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cid.setEnabled(false);
        cid.setOpaque(false);
        jPanel5.add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 200, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Citizen Id:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Last Name:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        clname.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        clname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        clname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        clname.setOpaque(false);
        clname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clnameActionPerformed(evt);
            }
        });
        jPanel5.add(clname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 200, 30));

        cgender.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cgender.setToolTipText("");
        jPanel5.add(cgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 100, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Gender:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Email:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        cemail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cemail.setOpaque(false);
        cemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cemailActionPerformed(evt);
            }
        });
        jPanel5.add(cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 200, 30));

        cstatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cstatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cstatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cstatus.setOpaque(false);
        cstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cstatusActionPerformed(evt);
            }
        });
        jPanel5.add(cstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 200, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Status:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        caddress.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        caddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        caddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(caddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 240, 230));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("Address:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 70, 230));

        ccontacts.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ccontacts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccontacts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ccontacts.setOpaque(false);
        ccontacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccontactsActionPerformed(evt);
            }
        });
        jPanel5.add(ccontacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 240, 30));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Contact:");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 70, -1));

        save.setBackground(new java.awt.Color(0, 102, 102));
        save.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        save.setForeground(new java.awt.Color(240, 240, 240));
        save.setText("SAVE");
        save.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
        });
        jPanel5.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 100, 30));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("First Name:");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        cfname.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cfname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cfname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cfname.setOpaque(false);
        jPanel5.add(cfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 200, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 790, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        close();
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void clnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clnameActionPerformed

    private void cemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cemailActionPerformed

    private void cstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cstatusActionPerformed

    private void ccontactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccontactsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccontactsActionPerformed

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        save.setBackground(bodycolor);
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
         dbConnector dbc = new dbConnector();

    if (cfname.getText().isEmpty() || clname.getText().isEmpty() || cemail.getText().isEmpty() ||
        caddress.getText().isEmpty() || cstatus.getText().isEmpty() || ccontacts.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill in all fields!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (action.equals("Add")) {
        String sql = "INSERT INTO tbl_citizen (c_fname, c_lname, c_gender, c_email, c_address, c_status, c_contact) " +
                     "VALUES ('" + cfname.getText() + "', '" + clname.getText() + "', '" + 
                     cgender.getSelectedItem().toString() + "', '" + cemail.getText() + "', '" + 
                     caddress.getText() + "', '" + cstatus.getText() + "', '" + ccontacts.getText() + "')";

        int result = dbc.insertData(sql);

        if (result == 1) {
            JOptionPane.showMessageDialog(null, "Citizen added successfully!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Error saving data!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } 
    else if (action.equals("Update")) {
        if (cid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error: No ID found for update!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sql = "UPDATE tbl_citizen SET c_fname = '" + cfname.getText() + 
                     "', c_lname = '" + clname.getText() + 
                     "', c_gender = '" + cgender.getSelectedItem().toString() +
                     "', c_email = '" + cemail.getText() +
                     "', c_address = '" + caddress.getText() +
                     "', c_status = '" + cstatus.getText() +
                     "', c_contact = '" + ccontacts.getText() + 
                     "' WHERE c_id = " + cid.getText();

        int result = dbc.insertData(sql);

        if (result == 1) {
            JOptionPane.showMessageDialog(null, "Citizen updated successfully!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Error updating data!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_saveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(citizenform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(citizenform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(citizenform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(citizenform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new citizenform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField caddress;
    public javax.swing.JTextField ccontacts;
    public javax.swing.JTextField cemail;
    public javax.swing.JTextField cfname;
    public javax.swing.JComboBox<String> cgender;
    public javax.swing.JTextField cid;
    public javax.swing.JTextField clname;
    private javax.swing.JLabel close;
    public javax.swing.JTextField cstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel minimize;
    public javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
